
# SEO settings
title: "Óc"
title2: " chó" # default: ""
description: "quả óc chó"
keywords: "blog, tech, deedee"
url: http://dee-dee.tk # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

favicon: dog.png
google_analytics: UA-XXXXX-XX
repo: http://github.com/deedev/
disqus_shortname: "dee-dee"
twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "dee-dee"
  job      : ""
  bio      : "Những suy nghĩ, chia sẻ trong quá trình học tập của một thanh niên thích ăn quả óc chó."
  thumb    : assets/images/author.jpg
  email    : nguyenduong199100@gmail.com
  url      : http://oc-cho.tk
  github   : http://github.com/deedev
  twitter  : http://twitter.com/
  facebook : https://www.facebook.com/wow.161621996
  linkedin : http://linkedin.com/in/

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
